### ISSUE TITLE
iOS permissions

### ISSUE THREAD

**Issue by xerotolerant** [bradmartin/nativescript-telegram-image-picker#1]
Hello, is this plugin tested with iOS?
I'm having difficulty with another image picker plugin. 
It allows me to pick the images and get either the url or the image data but not much else. 

Once the image is outside of the app folder I get the error:
 NSErrorWrapper: You don’t have permission to save the file “100APPLE” in the folder “DCIM”.

Is this something that happens with this plugin?

**Comment by bradmartin** [comment]
This doesn't work for iOS. Forgot to make note of that on the README, and I'll add a conditional check to the plugin source. Thanks for bringing this up 👍 

As for your other issue - no idea. You should try the image-picker plugin from the NativeScript team, it worked good for me last I used it.
