### ISSUE TITLE
Toast Message should be able to be customized

### ISSUE THREAD

**Issue by Daxito** [bradmartin/nativescript-telegram-image-picker#2]
Toast Message should be able to be customized, right now if I try to select more than the Max Pic selection then I get an error in some other language.

**Comment by damir9311** [comment]
How to customize this?

**Comment by bradmartin** [comment]
The capability to customize many things was added after I did the original abstraction on the native lib https://github.com/TangXiaoLv/TelegramGallery . To allow those options in this plugin we just need to update the dependency and then add the methods where necessary to expose new functionality from the native lib. I'm hoping in the next week or so I have some free time to update a few plugins but can't guarantee any time right now.

**Comment by bhavincb** [comment]
hii @bradmartin ,
any update to new functionality?

**Comment by bhavincb** [comment]
Have u fixed it?
